# Display
item:
  name: "<yellow>Pokeball"
  lore:
    - "<gray>You know what to do with it."
  custom-model-data: ~

# Capture rules
capture:
  allowed-entity-types:
    - COW
    - SHEEP
    - PIG
    - CHICKEN
    - RABBIT
    - VILLAGER
    - WOLF
    - CAT
    - HORSE
    - DONKEY
    - LLAMA
    - FOX
    - TURTLE
    - BEE
  consume-on-release: false

# Creative bypass
creative-bypass:
  enabled: true
  permission: pokeball.bypass.creative
  annotate: true
  annotation-line: "<gray>Captured via <red>Admin Bypass</red></gray>"

# Worlds where capture/release is allowed (empty = all)
compat:
  worlds: []

# Permissions (documented; enforcement in code)
permissions:
  use-capture: pokeball.use.capture
  use-release: pokeball.use.release
  admin-give: pokeball.admin.give
  admin-reload: pokeball.admin.reload

# Messages (MiniMessage)
messages:
  prefix: "<gray>[<yellow>Pokeball</yellow>]"
  capture-success: "<green>Captured a <yellow><type></yellow>!"
  capture-fail-blocked: "<red>You cannot capture that mob."
  capture-fail-invalid: "<red>Use a Pokeball on a valid mob."
  capture-fail-permission: "<red>You lack permission to capture."
  capture-fail-world: "<red>Capturing is not allowed in this world."
  release-success: "<green>Released a <yellow><type></yellow>."
  release-fail-empty: "<red>This Pokeball is empty."
  release-fail-permission: "<red>You lack permission to release."
  release-fail-world: "<red>Releasing is not allowed in this world."
  given: "<green>Gave <yellow><count></yellow> Pokeball(s) to <yellow><player></yellow>."
  reloaded: "<green>Configuration reloaded."
