name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -B -ntp package

      - name: Compute artifact name
        id: meta
        shell: bash
        run: |
          JAR=$(ls -1 target/Pokeball-*.jar | head -n 1)
          NAME=$(basename "$JAR")
          NAME_NO_EXT="${NAME%.jar}"
          echo "jar=$JAR" >> "$GITHUB_OUTPUT"
          echo "name=$NAME_NO_EXT" >> "$GITHUB_OUTPUT"

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.meta.outputs.name }}
          path: ${{ steps.meta.outputs.jar }}
          retention-days: 7
          if-no-files-found: error
