name: release-assets

on:
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: release-assets-${{ github.event.release.tag_name }}
  cancel-in-progress: true

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build JAR
        run: mvn -B -ntp clean package

      - name: Attach JAR to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            target/Pokeball-*.jar
          fail_on_unmatched_files: true
          overwrite_files: true
          token: ${{ secrets.ADMIN_TOKEN }}

