name: release-assets

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build JAR
        run: mvn -B -ntp clean package

      - name: Attach JAR to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/Pokeball-*.jar
          fail_on_unmatched_files: true

